version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: lms_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
    networks:
      - lms_network

  php-fpm:
    build:
      context: .
      dockerfile: docker/common/php-fpm/Dockerfile
    container_name: lms_php_fpm
    volumes:
      - ./:/var/www
    networks:
      - lms_network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: lms_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-lms}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-lms}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - lms_network

  redis:
    image: redis:alpine
    container_name: lms_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lms_network

  node:
    image: node:18-alpine
    container_name: lms_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - lms_network

networks:
  lms_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 